export default [
    {
        id:1,
        name:"sagar",
        rating:4.1,
        color:"bisque",
        address:[{
            city:"mumbai",
            code:400066
        }],
        food:["american","indian"]
    },
     {
         id:2,
        name:"pleasure",
        rating:5,
        color:"aquamarine",
        address:[{
            city:"pune",
            code:40001
        }],
        food:["spanish","poland"]
    },
     {
         id:3,
        name:"indianFood",
        rating:4.6,
        color:"wheat",
        address:[{
            city:"karnataka",
            code:4000669
        }],
        food:["southindian","brazil"]
    },
     {
         id:4,
        name:"anna",
        rating:2.5,
        color:"powderblue",
        address:[{
            city:"benglore",
            code:400062
        }],
        food:["italian","indian"]
    },
     {
         id:5,
        name:"italian",
        rating:4.7,
        color:"rgb(255, 255, 200)",
        address:[{
            city:"kerala",
            code:40078
        }],
        food:["kerala","indian","american"]
    },
    {
        id:6,
        name:"bluewhale",
        rating:2.1,
        color:"rgb(200, 255, 200)",
        address:[{
            city:"new york",
            code:2
        }],
        food:["italian","brazil","american"]
    }
]